services:
  pognaleey-back:
    container_name: pognaleey-back
    build:
      context: ./pognaleey-back
      dockerfile: Dockerfile
    depends_on:
      - dbpostgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      GPT_FOLDER_ID: ${GPT_FOLDER_ID}
      GPT_API_KEY: ${GPT_API_KEY}
      IMAGE_SEARCH_API_KEY: ${IMAGE_SEARCH_API_KEY}
      IMAGE_SEARCH_FOLDER_ID: ${IMAGE_SEARCH_FOLDER_ID}
  pognaleey-front:
    container_name: pognaleey-front
    build:
      context: ./pognaleey-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    volumes:
      - ./pognaleey-front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pognaleey-back
  dbpostgresql:
    image: postgres:17.2
    container_name: pognaleey-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
