CREATE TABLE IF NOT EXISTS form_data
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp NOT NULL,
    user_id INTEGER NOT NULL,
    content VARCHAR NOT NULL
);


-- Put every varchar size &  add constraints by your own