-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(31) UNIQUE NOT NULL,
    LOGIN      VARCHAR(31) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP          NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP          NOT NULL DEFAULT NOW()
);

CREATE TABLE TRAVEL_INQUIRIES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
--         USER_ID    BIGINT
--         NOT NULL REFERENCES USERS (ID)
--     ,
    PAYLOAD    VARCHAR   NOT NULL,
--     STATUS     VARCHAR(20),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE TRAVEL_RECOMMENDATIONS
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    INQUIRY_ID       BIGINT UNIQUE NOT NULL REFERENCES TRAVEL_INQUIRIES (ID),
    QUICK_PAYLOAD    VARCHAR       NOT NULL,
    DETAILED_PAYLOAD VARCHAR,
    CREATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW()
);