-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(31) UNIQUE NOT NULL,
    LOGIN      VARCHAR(31) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP          NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP          NOT NULL DEFAULT NOW()
);

CREATE TABLE TRAVEL_INQUIRIES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
--         USER_ID    BIGINT
--         NOT NULL REFERENCES USERS (ID)
--     ,
    PARAMS     VARCHAR   NOT NULL,
--     STATUS     VARCHAR(20),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE TRAVEL_RECOMMENDATIONS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    INQUIRY_ID        BIGINT    NOT NULL REFERENCES TRAVEL_INQUIRIES (ID),
    TITLE             VARCHAR   NOT NULL,
    SHORT_DESCRIPTION VARCHAR   NOT NULL,
    DETAILS           VARCHAR,
    IMAGE_URL         VARCHAR,
    CREATED_AT        TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT inquiry_id_title UNIQUE (INQUIRY_ID, TITLE)
);