CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(31)  NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE travel_inquiries
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    params     VARCHAR   NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE travel_recommendations
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id        BIGINT    NOT NULL REFERENCES travel_inquiries (ID),
    title             VARCHAR   NOT NULL,
    short_description VARCHAR   NOT NULL,
    details           VARCHAR,
    image_url         VARCHAR,
    created_at        TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT inquiry_id_title UNIQUE (inquiry_id, title)
);