CREATE TABLE travel_guide_content_items
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guide_id BIGINT  NOT NULL UNIQUE REFERENCES travel_guides (id),
    content  TEXT,
    ordinal  INT     NOT NULL,
    status   VARCHAR NOT NULL
);

CREATE INDEX idx_travel_guide_content_items_guide_id ON travel_guide_content_items (guide_id);

INSERT INTO travel_guide_content_items (guide_id, content, ordinal, status)
SELECT id, details, 1, 'READY'
FROM travel_guides
WHERE details IS NOT NULL;

DELETE
FROM travel_guides
WHERE details IS NULL;

ALTER TABLE travel_guides
    DROP COLUMN details;