CREATE TABLE images
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    title         VARCHAR   NOT NULL,
    url           VARCHAR   NOT NULL,
    thumbnail_url VARCHAR   NOT NULL,
    query         VARCHAR   NOT NULL
);

ALTER TABLE travel_recommendations
    ADD COLUMN image_id BIGINT REFERENCES images (id);

ALTER TABLE travel_guides
    ADD COLUMN image_id BIGINT REFERENCES images (id);

INSERT INTO images (created_at, title, url, thumbnail_url, query)
SELECT r.created_at, r.title, r.image_url, r.image_url, r.image_search_phrase
from travel_recommendations r
where image_url IS NOT NULL;

UPDATE travel_recommendations r
SET image_id = i.id
FROM images i
WHERE i.query = r.image_search_phrase
  AND i.title = r.title;

UPDATE travel_guides g
SET image_id = r.image_id
FROM travel_recommendations r
WHERE g.recommendation_id = r.id;

ALTER TABLE travel_recommendations
    DROP COLUMN image_url,
    DROP COLUMN image_search_phrase;

ALTER TABLE travel_guides
    DROP COLUMN image_url;