CREATE TABLE resource
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    name       VARCHAR(255) NOT NULL,
    data       BYTEA        NOT NULL
);

ALTER table images
    ADD COLUMN ai_generated BOOLEAN;

UPDATE images
SET ai_generated = FALSE
WHERE ai_generated IS NULL;

ALTER TABLE images
    ALTER COLUMN ai_generated SET NOT NULL;

ALTER TABLE images
    RENAME COLUMN owner_name TO author_name;

ALTER TABLE images
    RENAME COLUMN owner_url TO author_url;

UPDATE travel_guide_content_items
SET content = jsonb_set(
                      jsonb_set(
                              content::jsonb,
                              '{authorName}',
                              content::jsonb -> 'ownerName'
                      ) - 'ownerName',
                      '{authorUrl}',
                      content::jsonb -> 'ownerUrl'
              ) - 'ownerUrl'
WHERE (content::jsonb ? 'ownerName' OR content::jsonb ? 'ownerUrl')
  and content like '{%';