server:
  servlet:
    context-path: /api/v1
  port: 8080
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: pognaleey
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 3MB  # Максимальный размер одного файла
      max-request-size: 5MB  # Максимальный размер всего запроса
logging:
  level:
    root: INFO
image-search-client:
  # noinspection SpringBootApplicationYaml
  current: ${CURRENT_IMAGE_SEARCH_CLIENT}
  openverse:
    base-url: https://api.openverse.org/v1/images/
gpt-client:
  # noinspection SpringBootApplicationYaml
  current: ${CURRENT_GPT_CLIENT}
  openai:
    base-url: https://api.openai.com/v1/chat/completions
    model: gpt-4o-mini
    api-key: ${CHAT_GPT_API_KEY}
jwt:
  secret: ${JWT_SECRET}
  token-validity-time-minutes: 34560 # 1 week
app:
  domain-name: ${APP_DOMAIN_NAME}