server:
  servlet:
    context-path: /api/v1
  port: 8080
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: pognaleey
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  profiles:
    active: dev
logging:
  level:
    root: INFO
image-search-client:
  base-url: https://yandex.ru/images-xml
  api-key: ${IMAGE_SEARCH_API_KEY}
  folder-id: ${IMAGE_SEARCH_FOLDER_ID}
  sleep-between-requests-ms: 1000
gpt-client:
  base-url: https://llm.api.cloud.yandex.net/foundationModels/v1/completion
  model-uri: gpt://b1g4e7108ae9pp9j7tn7/yandexgpt/rc
  folder-id: ${GPT_FOLDER_ID}
  api-key: ${GPT_API_KEY}
jwt:
  secret: ${JWT_SECRET}
  token-validity-time-minutes: 1440 # 24 hours
