server:
  servlet:
    context-path: /api/v1
  port: 8080
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: pognaleey
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  profiles:
    active: local
logging:
  level:
    root: INFO
image-search-client:
  api-key: apiKey
  folder-id: folderId
gpt-client:
  folder-id: folderId
  api-key: apiKey
  url: url
  model-uri: modelUri
